---

- name: hashes
  manala_merge_hashes:
    hashes: "{{ item.hashes }}"
    prefix: "{{ item.prefix|default(omit) }}"
    var:    "{{ item.var|default(omit) }}"
  with_items: "{{ manala_merge_hashes }}"
